import os

# WhatsApp Business API Configuration
WHATSAPP_ACCESS_TOKEN = "EAAYLvZBaHbvYBPCVm9vSkuFOnj2lKZANLLTOIIpkSBmCu2UqaUWH0EqJtPheiVvlekjW5ZADyIWgzkUY2ZBFdQ4UJ9jLjAuZBOeMAuGO3l0AUDEV9lPC0STyaJLAysB19afNRg3hkvciaHwARjhGw55thchImzZCx8JsKCbZC5IZBHZApifBIrw5ZBX5B66v6JCZC4uahtXj6ZAdSxXaTxf6EhaBrxuErTVYGlZBa9Nkp2ZAe3S60ZD"
WHATSAPP_PHONE_NUMBER_ID = "762257780294903"

# Set environment variables if they're not already set
if not os.getenv('WHATSAPP_ACCESS_TOKEN'):
    os.environ['WHATSAPP_ACCESS_TOKEN'] = WHATSAPP_ACCESS_TOKEN

if not os.getenv('WHATSAPP_PHONE_NUMBER_ID'):
    os.environ['WHATSAPP_PHONE_NUMBER_ID'] = WHATSAPP_PHONE_NUMBER_ID

# Default template name
DEFAULT_TEMPLATE_NAME = "receita1"
DEFAULT_TEMPLATE_LANGUAGE = "pt_BR"